### ISSUE TITLE
Sink vectors could not be created

### ISSUE THREAD

**Issue by maxibor** [CamilaDuitama/decOM#6]
Hi @CamilaDuitama ,
I'm trying decOM, but I'm running into the following issue:

```bash
$ decOM -s SRR13355807 -p_sources decOM_sources/ -k tests/sample/SRR13355807.fof -mem 10GB -t 5
[2024-10-14 12:03:37.542] [warning] -plot parameter has been set to True
[2024-10-14 12:04:12.044] [status] Starting decOM version: 1.1
[2024-10-14 12:04:12.045] [status] Arguments decOM:
sink: SRR13355807,p_sinks: None,p_sources: decOM_sources/,key: tests/sample/SRR13355807.fof,p_keys: None,t: 5,plt: True,mem: 10GB,o: decOM_output/
[2024-10-14 12:04:12.120] [error] [Errno 2] No such file or directory: 'kmtricks'
[2024-10-14 12:04:12.121] [warning] .vec files in decOM_output/SRR13355807_vector/matrices/ folder could not be concatenated as there are no .vec files in the folder.
[2024-10-14 12:04:12.121] [error] Sink vector for SRR13355807 could not be created, verify your input files are correct
```

I'm using decOM installed through bioconda (v0.32?) which is version 1.1 with the test data you provided on zenodo.

So a minimal reproducible example would be something like:
```bash
conda create -n decom -c bioconda decom numpy=1.26.0
conda activate decom
wget https://zenodo.org/record/6513520/files/decOM_sources.tar.gz  
tar -xf decOM_sources.tar.gz
decOM -s SRR13355807 -p_sources decOM_sources/ -k tests/sample/SRR13355807.fof -mem 10GB -t 5 
```

**Comment by CamilaDuitama** [comment]
Hi @maxibor !

Thank you for using and testing decOM. 

`kmtricks`, an essential dependency for `decOM`, is not present in your environment. The error message 

> [Errno 2] No such file or directory: 'kmtricks'

 indicates that the tool is not installed or not found in the system's PATH.

To resolve this issue, you will need to ensure that kmtricks is installed within your conda environment. `kmtricks` can be installed from the conda-forge and tlemane channels using the following conda command:

`conda install -c conda-forge -c tlemane kmtricks
`

However, I recommend setting up the decOM environment using the environment file provided with the repository, which is intended to handle all the dependencies automatically. Here's the step-by-step process:

```
git clone https://github.com/CamilaDuitama/decOM.git  
cd decOM  
conda env create -n decOM --file environment.yml  
conda deactivate
conda activate decOM  
```
This environment file includes all necessary packages, and the correct versions, including `kmtricks`. Using the environment.yml ensures that you have compatible versions of all dependencies for `decOM`to work.

Let me know if it helped :)

**Comment by maxibor** [comment]
Hey @CamilaDuitama ,
If `kmtricks` is an essential dependancy of decOM, could you add it the the bioconda recipe ?

I see that it's already on bioconda itself, so it should be just a simple addition here https://github.com/bioconda/bioconda-recipes/blob/d073aa992e4d4b9f10089d228e2cae83625ebd0e/recipes/decom/meta.yaml#L30

Having a single self-contained bioconda package makes it much easier to integrate it into containers and computational pipelines.

**Comment by CamilaDuitama** [comment]
Done! See: https://github.com/bioconda/bioconda-recipes/pull/51723
Thanks for the suggestion and your help :)
